name: dart_mpd
description: a dart package which implements the MPD protocol. https://www.musicpd.org/
version: 0.5.0
repository: https://github.com/robertodoering/dart_mpd

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  file: ^7.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  platform: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.6.1
  lints: ^5.1.1
  test: ^1.24.0
