name: dart_mpd
description: a dart package which implements the MPD protocol. https://www.musicpd.org/
version: 0.1.2
repository: https://github.com/robertodoering/dart_mpd

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  file: ^6.1.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  platform: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.24.0
